/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * View.java
 *
 * Created on 09/05/2012, 14:57:16
 */
package Grafos.desenho;

import Grafos.AGM;
import Grafos.BuscaLargura;
import Grafos.Caminho;
import Grafos.Coloracao;
import Grafos.ComponentesConexas;
import Grafos.Conectividade;
import Grafos.Grafo;
import Grafos.ListaAdjacencia;
import Grafos.Representacao;
import Grafos.Topologia;
import Grafos.Transposta;
import Grafos.desenho.color.GrayScale;
import Grafos.desenho.color.RainbowScale;
import Maze.Lab;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.RenderingHints;
import java.awt.event.MouseWheelEvent;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Danilo Medeiros Eler
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        this.view = new ViewPanel();
        //this.view.setGraph(this.graph);
        initComponents();
        this.m_algoritmos.setEnabled(false);
        this.mi_maze.setEnabled(false);
        this.mi_salvarImagem.setEnabled(false);
    }

    private Graph geraGraph(Representacao rep, int[] ant) {

        int numvert = rep.getNumVertices();
        Graph g = new Graph(numvert, 0);
        for (int i = 0; i < numvert; i++) {
            if (ant[i] != -1) {
                Vertex v1 = g.getVertex().get(i);
                Vertex v2 = g.getVertex().get(ant[i]);

                g.addEdge(new Edge(v1, v2, rep.getVal(i, ant[i]), false));
            }
        }

        return g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane(this.view);
        p_thePanel = new javax.swing.JPanel();
        p_Vazio = new javax.swing.JPanel();
        p_busca = new javax.swing.JPanel();
        bt_busca = new javax.swing.JButton();
        tf_busca = new javax.swing.JTextField();
        lb_busca = new javax.swing.JLabel();
        p_maze = new javax.swing.JPanel();
        lb_entradaMaze = new javax.swing.JLabel();
        lb_saidaMaze = new javax.swing.JLabel();
        lb_xEntradaMaze = new javax.swing.JLabel();
        lb_yEntradaMaze = new javax.swing.JLabel();
        tf_xEntradaMaze = new javax.swing.JTextField();
        tf_yEntradaMaze = new javax.swing.JTextField();
        lb_xSaidaMaze = new javax.swing.JLabel();
        tf_xSaidaMaze = new javax.swing.JTextField();
        lb_ySaidaMaze = new javax.swing.JLabel();
        tf_ySaidaMaze = new javax.swing.JTextField();
        bt_goMaze = new javax.swing.JButton();
        paredeToggle = new javax.swing.JToggleButton();
        caminhoToggle = new javax.swing.JToggleButton();
        p_gerar = new javax.swing.JPanel();
        lb_gerar = new javax.swing.JLabel();
        tf_gerar = new javax.swing.JTextField();
        bt_gerar = new javax.swing.JButton();
        p_caminho = new javax.swing.JPanel();
        bt_caminho = new javax.swing.JButton();
        tf_caminho = new javax.swing.JTextField();
        lb_caminho = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        m_opcoes = new javax.swing.JMenu();
        mi_carregarGrafo = new javax.swing.JMenuItem();
        mi_salvarImagem = new javax.swing.JMenuItem();
        m_algoritmos = new javax.swing.JMenu();
        mi_compConexas = new javax.swing.JMenuItem();
        mi_coloracao = new javax.swing.JMenuItem();
        mi_AGM = new javax.swing.JMenuItem();
        mi_caminhoMin = new javax.swing.JMenuItem();
        mi_conectividade = new javax.swing.JMenuItem();
        mi_transposta = new javax.swing.JMenuItem();
        mi_ordemTopologica = new javax.swing.JMenuItem();
        mi_buscaLargura = new javax.swing.JMenuItem();
        m_aplicacao = new javax.swing.JMenu();
        mi_maze = new javax.swing.JMenuItem();
        mi_criaMaze = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_thePanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout p_VazioLayout = new javax.swing.GroupLayout(p_Vazio);
        p_Vazio.setLayout(p_VazioLayout);
        p_VazioLayout.setHorizontalGroup(
            p_VazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        p_VazioLayout.setVerticalGroup(
            p_VazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        p_thePanel.add(p_Vazio, "cardVazio");
        p_Vazio.getAccessibleContext().setAccessibleName("");

        p_busca.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca em Largura"));

        bt_busca.setText("Buscar");
        bt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscaActionPerformed(evt);
            }
        });

        lb_busca.setText("Vértice Inicial:");

        javax.swing.GroupLayout p_buscaLayout = new javax.swing.GroupLayout(p_busca);
        p_busca.setLayout(p_buscaLayout);
        p_buscaLayout.setHorizontalGroup(
            p_buscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_buscaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lb_busca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(bt_busca)
                .addGap(60, 60, 60))
        );
        p_buscaLayout.setVerticalGroup(
            p_buscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_buscaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(p_buscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_busca))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        p_thePanel.add(p_busca, "cardBusca");

        lb_entradaMaze.setText("Entrada:");

        lb_saidaMaze.setText("Saída:");

        lb_xEntradaMaze.setText("X");

        lb_yEntradaMaze.setText("Y");

        lb_xSaidaMaze.setText("X");

        lb_ySaidaMaze.setText("Y");

        bt_goMaze.setText("GO!!");
        bt_goMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_goMazeActionPerformed(evt);
            }
        });

        paredeToggle.setText("Mostrar Paredes");
        paredeToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paredeToggleActionPerformed(evt);
            }
        });

        caminhoToggle.setText("Esconder Caminho");
        caminhoToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_mazeLayout = new javax.swing.GroupLayout(p_maze);
        p_maze.setLayout(p_mazeLayout);
        p_mazeLayout.setHorizontalGroup(
            p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mazeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mazeLayout.createSequentialGroup()
                        .addGroup(p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_entradaMaze)
                            .addGroup(p_mazeLayout.createSequentialGroup()
                                .addComponent(lb_xEntradaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_xEntradaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_yEntradaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_yEntradaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_saidaMaze)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mazeLayout.createSequentialGroup()
                        .addComponent(lb_xSaidaMaze)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_xSaidaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_ySaidaMaze)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_ySaidaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addGroup(p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caminhoToggle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paredeToggle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_goMaze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        p_mazeLayout.setVerticalGroup(
            p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mazeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_entradaMaze)
                    .addComponent(paredeToggle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mazeLayout.createSequentialGroup()
                        .addGroup(p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_xEntradaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_yEntradaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_xEntradaMaze)
                            .addComponent(lb_yEntradaMaze))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mazeLayout.createSequentialGroup()
                        .addComponent(caminhoToggle)
                        .addGap(7, 7, 7)))
                .addGroup(p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mazeLayout.createSequentialGroup()
                        .addComponent(lb_saidaMaze)
                        .addGap(9, 9, 9)
                        .addGroup(p_mazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_xSaidaMaze)
                            .addComponent(tf_xSaidaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ySaidaMaze)
                            .addComponent(tf_ySaidaMaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_goMaze))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_thePanel.add(p_maze, "cardMaze");

        lb_gerar.setText("Vértice Inicial:");

        bt_gerar.setText("Gerar");
        bt_gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_gerarLayout = new javax.swing.GroupLayout(p_gerar);
        p_gerar.setLayout(p_gerarLayout);
        p_gerarLayout.setHorizontalGroup(
            p_gerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gerarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_gerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_gerar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                .addComponent(bt_gerar)
                .addGap(31, 31, 31))
        );
        p_gerarLayout.setVerticalGroup(
            p_gerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gerarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(p_gerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_gerar)
                    .addComponent(tf_gerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_gerar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        p_thePanel.add(p_gerar, "cardGerar");

        p_caminho.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca em Largura"));

        bt_caminho.setText("Buscar");
        bt_caminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_caminhoActionPerformed(evt);
            }
        });

        lb_caminho.setText("Vértice Inicial:");

        javax.swing.GroupLayout p_caminhoLayout = new javax.swing.GroupLayout(p_caminho);
        p_caminho.setLayout(p_caminhoLayout);
        p_caminhoLayout.setHorizontalGroup(
            p_caminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_caminhoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lb_caminho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_caminho, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(bt_caminho)
                .addGap(60, 60, 60))
        );
        p_caminhoLayout.setVerticalGroup(
            p_caminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_caminhoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(p_caminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_caminho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_caminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_caminho))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        p_thePanel.add(p_caminho, "cardCaminho");

        m_opcoes.setText("Opções");

        mi_carregarGrafo.setText("Carregar Grafo");
        mi_carregarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_carregarGrafoActionPerformed(evt);
            }
        });
        m_opcoes.add(mi_carregarGrafo);

        mi_salvarImagem.setText("Salvar Imagem");
        mi_salvarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_salvarImagemActionPerformed(evt);
            }
        });
        m_opcoes.add(mi_salvarImagem);

        menuBar.add(m_opcoes);

        m_algoritmos.setText("Algoritmos");

        mi_compConexas.setText("Marcar Componentes Conexas");
        mi_compConexas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_compConexasActionPerformed(evt);
            }
        });
        m_algoritmos.add(mi_compConexas);

        mi_coloracao.setText("Coloração");
        mi_coloracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_coloracaoActionPerformed(evt);
            }
        });
        m_algoritmos.add(mi_coloracao);

        mi_AGM.setText("Árvore Geradora Mínima");
        mi_AGM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_AGMActionPerformed(evt);
            }
        });
        m_algoritmos.add(mi_AGM);

        mi_caminhoMin.setText("Caminho Mínimo");
        mi_caminhoMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_caminhoMinActionPerformed(evt);
            }
        });
        m_algoritmos.add(mi_caminhoMin);

        mi_conectividade.setText("Conectividade");
        mi_conectividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_conectividadeActionPerformed(evt);
            }
        });
        m_algoritmos.add(mi_conectividade);

        mi_transposta.setText("Transposição");
        mi_transposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_transpostaActionPerformed(evt);
            }
        });
        m_algoritmos.add(mi_transposta);

        mi_ordemTopologica.setText("Ordem Topológica");
        mi_ordemTopologica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ordemTopologicaActionPerformed(evt);
            }
        });
        m_algoritmos.add(mi_ordemTopologica);

        mi_buscaLargura.setText("Busca em Largura");
        mi_buscaLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_buscaLarguraActionPerformed(evt);
            }
        });
        m_algoritmos.add(mi_buscaLargura);

        menuBar.add(m_algoritmos);

        m_aplicacao.setText("Aplicação");

        mi_maze.setText("Labirinto");
        mi_maze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_mazeActionPerformed(evt);
            }
        });
        m_aplicacao.add(mi_maze);

        mi_criaMaze.setText("Gerar Labirinto");
        mi_criaMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_criaMazeActionPerformed(evt);
            }
        });
        m_aplicacao.add(mi_criaMaze);

        menuBar.add(m_aplicacao);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
            .addComponent(p_thePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(p_thePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_carregarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_carregarGrafoActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("C:\\Users\\fabio\\Desktop\\Aulas\\Grafos\\arq");
        int result;
        result = fc.showOpenDialog(null);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            String filename = fc.getSelectedFile().getAbsolutePath();
            BufferedReader in = null;
            try {
                in = new BufferedReader(new FileReader(filename));
                ////////LEMBRAR DE VERIFICAR SE É GRAFO OU DÍGRAFO
                ////////FAZER O TRATAMENTO NA INSERÇÃO DOS DADOS NA ESTRUTURA
                int grafo = Integer.parseInt(in.readLine());

                //le numero de vertices
                int nVert = Integer.parseInt(in.readLine());
                this.graph = new Graph(nVert, grafo); ///desenho
                this.grafo = new Grafo(nVert, grafo, new ListaAdjacencia()); ///estrutura de dados

                //leitura das arestas
                String line;
                while ((line = in.readLine()) != null && line.trim().length() > 0) {
                    StringTokenizer t1 = new StringTokenizer(line, " ");
                    int vIni = Integer.parseInt(t1.nextToken().trim()); //verticeInicial
                    int vFim = Integer.parseInt(t1.nextToken().trim()); //verticeFinal
                    int peso = Integer.parseInt(t1.nextToken().trim()); //Peso
                    Vertex vS = this.graph.getVertex().get(vIni);
                    Vertex vT = this.graph.getVertex().get(vFim);
                    this.grafo.addAresta(vIni, vFim, peso); //estrutura de dados
                    Edge e = new Edge(vS, vT, peso, this.graph.isOriented()); //desenho

                    this.graph.addEdge(e);    //desenho

                }  //se tiver peso nas arestas, adicionar mais uma leitura de token

                this.view.setGraph(graph);

                this.backUpGraph = this.graph.clone();

                if (grafo == 0) {
                    this.mi_compConexas.setEnabled(true);
                    this.mi_coloracao.setEnabled(true);
                    this.mi_conectividade.setEnabled(false);
                    this.mi_transposta.setEnabled(false);
                    this.mi_ordemTopologica.setEnabled(false);

                    ComponentesConexas cc = new ComponentesConexas();
                    cc.execute(this.grafo);

                    if (cc.getNumComponentes() > 1) {
                        this.mi_AGM.setEnabled(false);
                        this.setTitle("Grafo - Não Conexo");
                    } else {
                        this.mi_AGM.setEnabled(true);
                        this.setTitle("Grafo - Conexo");
                    }
                } else {
                    this.mi_compConexas.setEnabled(false);
                    this.mi_coloracao.setEnabled(false);
                    this.mi_AGM.setEnabled(false);
                    this.mi_conectividade.setEnabled(true);
                    this.mi_transposta.setEnabled(true);

                    Conectividade conec = new Conectividade();
                    conec.execute(this.grafo);

                    if (conec.getNumComp() == nVert) {
                        this.mi_ordemTopologica.setEnabled(true);
                        this.setTitle("Dígrafo - Acíclico");
                    } else {
                        this.mi_ordemTopologica.setEnabled(false);
                        this.setTitle("Dígrafo - Cíclico");
                    }

                }
                this.m_algoritmos.setEnabled(true);
                this.mi_maze.setEnabled(true);
                this.mi_salvarImagem.setEnabled(true);

                this.ap = false;

                CardLayout card = (CardLayout) p_thePanel.getLayout();
                card.show(p_thePanel, "cardVazio");

            } catch (IOException ex) {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                //fechar o arquivo
                if (in != null) {
                    try {
                        in.close();
                    } catch (IOException ex) {
                        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_mi_carregarGrafoActionPerformed

    private void mi_salvarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_salvarImagemActionPerformed
        // TODO add your handling code here:
        JFileChooser dialog = new JFileChooser();
        dialog.setMultiSelectionEnabled(false);
        dialog.setDialogTitle("Save file");
        dialog.setCurrentDirectory(new File("D:\\DANILO\\UNESP\\2017\\Aulas\\Grafos"));
        int result = dialog.showDialog(this, "Salvar");
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                String filename = dialog.getSelectedFile().getAbsolutePath();
                this.view.saveToPngImageFile(filename);
            } catch (IOException ex) {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mi_salvarImagemActionPerformed

    private void mi_compConexasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_compConexasActionPerformed
        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardVazio");
        this.ap = false;

        graph = this.backUpGraph.clone();
        ComponentesConexas componentesConexas = new ComponentesConexas();
        componentesConexas.execute(grafo);
        int comp[] = componentesConexas.getComponentes();
        int numComp = componentesConexas.getNumComponentes();
        int compStep = 255 / numComp;
        RainbowScale rbS = new RainbowScale();
        for (int i = 0; i < comp.length; i++) {
            this.graph.getVertex().get(i).setColor(rbS.getColor(comp[i] * compStep));
        }
        this.view.cleanImage();
        this.view.repaint();
    }//GEN-LAST:event_mi_compConexasActionPerformed

    private void mi_coloracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_coloracaoActionPerformed
        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardVazio");
        this.ap = false;

        graph = this.backUpGraph.clone();

        Coloracao coloracao = new Coloracao();
        coloracao.execute(grafo);
        int cores[] = coloracao.getCores();
        int nCores = coloracao.getNumCores();

        int coresStep = 255 / nCores;
        RainbowScale rbS = new RainbowScale();
        for (int i = 0; i < cores.length; i++) {
            this.graph.getVertex().get(i).setColor(rbS.getColor(cores[i] * coresStep));
        }
        this.view.cleanImage();
        this.view.repaint();
    }//GEN-LAST:event_mi_coloracaoActionPerformed

    private void mi_AGMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_AGMActionPerformed
        p_busca.setBorder(BorderFactory.createTitledBorder("Árvore Geradora Mínima"));

        graph = this.backUpGraph.clone();
        this.view.cleanImage();
        this.view.repaint();

        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardGerar");
        this.ap = false;
        this.tf_gerar.setText("");


    }//GEN-LAST:event_mi_AGMActionPerformed

    private void mi_conectividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_conectividadeActionPerformed
        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardVazio");
        this.ap = false;

        graph = this.backUpGraph.clone();
        Conectividade componentesConexas = new Conectividade();
        componentesConexas.execute(grafo);
        int comp[] = componentesConexas.getComponente();
        int numComp = componentesConexas.getNumComp();
        int compStep = 255 / numComp;
        RainbowScale rbS = new RainbowScale();
        for (int i = 0; i < comp.length; i++) {
            this.graph.getVertex().get(i).setColor(rbS.getColor(comp[i] * compStep));
        }
        this.view.cleanImage();
        this.view.repaint();

    }//GEN-LAST:event_mi_conectividadeActionPerformed

    private void mi_buscaLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_buscaLarguraActionPerformed
        p_busca.setBorder(BorderFactory.createTitledBorder("Busca em Largura"));

        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardBusca");
        this.tf_busca.setText("");

    }//GEN-LAST:event_mi_buscaLarguraActionPerformed

    private void mi_ordemTopologicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ordemTopologicaActionPerformed
        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardVazio");
        this.ap = false;

        this.topologia = true;

        Topologia topsort = new Topologia();
        topsort.execute(grafo);
        this.graph = new Graph(topsort.getOrdem(), (ArrayList<Edge>) this.graph.getEdges().clone());

        this.view.cleanImage();
        this.view.repaint();


    }//GEN-LAST:event_mi_ordemTopologicaActionPerformed

    private void mi_transpostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_transpostaActionPerformed
        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardVazio");
        this.ap = false;

        Transposta transp = new Transposta();

        transp.execute(grafo);

        this.graph = new Graph(transp.getTransposto());
        this.view.cleanImage();
        this.view.repaint();
    }//GEN-LAST:event_mi_transpostaActionPerformed

    private void mi_caminhoMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_caminhoMinActionPerformed
        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardCaminho");
        this.ap = false;
    }//GEN-LAST:event_mi_caminhoMinActionPerformed

    private void bt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscaActionPerformed

        int ini;
        this.graph = this.backUpGraph.clone();
        BuscaLargura busca = new BuscaLargura();
        try {
            ini = Integer.valueOf(this.tf_busca.getText());
            if (ini < 0 || ini >= this.grafo.getRepresentacao().getNumVertices()) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Numero Inválido");
            return;
        }
        busca.execute(grafo, ini);

        int[] caminho = busca.getCaminho();

        this.graph.buscaLargura(caminho);

        this.view.setGraph(this.graph);
        this.view.cleanImage();

        this.view.repaint();


    }//GEN-LAST:event_bt_buscaActionPerformed

    private void bt_goMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_goMazeActionPerformed
        int xi, yi, xf, yf;

        graph = this.backUpGraph.clone();

        graph.setApp(true);
        try {
            xi = Integer.valueOf(this.tf_xEntradaMaze.getText());
            yi = Integer.valueOf(this.tf_yEntradaMaze.getText());

            xf = Integer.valueOf(this.tf_xSaidaMaze.getText());
            yf = Integer.valueOf(this.tf_ySaidaMaze.getText());

            if (xi * col + yi > this.grafo.getRepresentacao().getNumVertices() || xf * col + yf > this.grafo.getRepresentacao().getNumVertices() || xi < 0 || yi < 0 || xf < 0 || yf < 0 || yi >= col || yf >= col) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Coordenadas Inválidas");
            return;
        }

        BuscaLargura busca = new BuscaLargura();
        int vi = (xi * col) + yi;
        int vf = (xf * col) + yf;
        busca.execute(grafo, vi);

        graph.caminho(busca.getCaminho(), vi, vf);

        this.view.setGraph(this.graph);
        this.view.cleanImage();

        this.view.repaint();
    }//GEN-LAST:event_bt_goMazeActionPerformed

    private void mi_criaMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_criaMazeActionPerformed
        Lab maze;

        try {
            int lin = Integer.valueOf(JOptionPane.showInputDialog("Numero de linhas:"));
            int col = Integer.valueOf(JOptionPane.showInputDialog("Numero de colunas:"));

            maze = new Lab(lin, col);

            maze.gravaArq();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Numero Inválido");
        }
    }//GEN-LAST:event_mi_criaMazeActionPerformed

    private void bt_gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerarActionPerformed
        AGM a = new AGM();
        int vert;
        this.graph = this.backUpGraph.clone();
        try {
            String opc = this.tf_gerar.getText();
            vert = Integer.valueOf(opc);
            a.execute(grafo, vert);
            graph.agm(a.getAnt());

        } catch (Exception e) {
            return;
        } finally {

            this.view.cleanImage();
            this.view.repaint();
        }
    }//GEN-LAST:event_bt_gerarActionPerformed

    private void paredeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paredeToggleActionPerformed
        this.isLab = this.paredeToggle.isSelected();

        this.view.cleanImage();
        this.view.repaint();
    }//GEN-LAST:event_paredeToggleActionPerformed

    private void caminhoToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoToggleActionPerformed
        this.view.cleanImage();
        this.view.repaint();
    }//GEN-LAST:event_caminhoToggleActionPerformed

    private void mi_mazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_mazeActionPerformed
        CardLayout card = (CardLayout) p_thePanel.getLayout();
        card.show(p_thePanel, "cardMaze");
        this.graph = this.backUpGraph.clone();
        this.tf_xEntradaMaze.setText("");
        this.tf_xSaidaMaze.setText("");
        this.tf_yEntradaMaze.setText("");
        this.tf_ySaidaMaze.setText("");
        this.ap = true;
        this.caminhoToggle.setSelected(true);
        this.paredeToggle.setSelected(true);
        this.col = this.grafo.getRepresentacao().getAdj(0).getPeso();
        this.graph.computeMazePosition(col);

        this.view.setGraph(this.graph);
        this.view.cleanImage();
        this.view.repaint();
    }//GEN-LAST:event_mi_mazeActionPerformed

    private void bt_caminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_caminhoActionPerformed
        int ini;
        this.graph = this.backUpGraph.clone();
        Caminho caminho = new Caminho();
        try {
            ini = Integer.valueOf(this.tf_caminho.getText());
            if (ini < 0 || ini >= this.grafo.getRepresentacao().getNumVertices()) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Numero Inválido");
            return;
        }
        caminho.execute(grafo, ini);

        int[] ant = caminho.getAnt();

        this.graph.buscaLargura(ant);

        this.view.setGraph(this.graph);
        this.view.cleanImage();
        this.view.repaint();
    }//GEN-LAST:event_bt_caminhoActionPerformed

    public class ViewPanel extends JPanel {

        public ViewPanel() {
            this.setBackground(java.awt.Color.WHITE);
            this.setLayout(new FlowLayout(FlowLayout.LEFT));
        }

        @Override
        public void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
            ////configuração do rendering para obeter melhor qualidade
            g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            g2.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
            g2.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
            g2.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);

            if (graph != null && this.imageBuffer == null) {
                this.imageBuffer = new BufferedImage(graph.getSize().width + 1,
                        graph.getSize().height + 1, BufferedImage.TYPE_INT_RGB);

                java.awt.Graphics2D g2Buffer = this.imageBuffer.createGraphics();
                g2Buffer.setColor(this.getBackground());
                g2Buffer.fillRect(0, 0, graph.getSize().width + 1, graph.getSize().height + 1);

                g2Buffer.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                if (topologia) {
                    graph.drawTopo(g2Buffer);
                    topologia = false;
                } else if (!ap || !caminhoToggle.isSelected()) {
                    graph.draw(g2Buffer);

                }
                if (paredeToggle.isSelected() && ap) {
                    graph.drawLab(g2Buffer, grafo, col);
                    isLab = false;
                }

                g2Buffer.dispose();
            }

            if (this.imageBuffer != null) {
                g2.drawImage(this.imageBuffer, 0, 0, null);
            }
        }

        public void saveToPngImageFile(String filename) throws IOException {
            try {
                //this.paint(this.imageBuffer.getGraphics());
                ImageIO.write(this.imageBuffer, "png", new File(filename));
            } catch (IOException ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
            }
        }

        public void setGraph(Graph graph) {
            if (graph != null) {
                this.setPreferredSize(new Dimension(graph.getSize().width * 2,
                        graph.getSize().height * 2));
                this.setSize(new Dimension(graph.getSize().width * 2,
                        graph.getSize().height * 2));

                this.cleanImage();
                this.repaint();
            }
        }

        public Vertex getMarkedVertex() {
            return markedVertex;
        }

        public void cleanImage() {
            this.imageBuffer = null;
        }

        public void adjustPanel() {
            float iniX = graph.getVertex().get(0).getX();
            float iniY = graph.getVertex().get(0).getY();
            float max_x = iniX, max_y = iniX;
            float min_x = iniY, min_y = iniY;
            int zero = graph.getVertex().get(0).getRay() * 5 + 10;

            for (int i = 1; i < graph.getVertex().size(); i++) {
                float x = graph.getVertex().get(i).getX();
                if (max_x < x) {
                    max_x = x;
                } else if (min_x > x) {
                    min_x = x;
                }

                float y = graph.getVertex().get(i).getY();
                if (max_y < y) {
                    max_y = y;
                } else if (min_y > y) {
                    min_y = y;
                }
            }

            for (Vertex v : graph.getVertex()) {
                v.setX(v.getX() + zero - min_x);
                v.setY(v.getY() + zero - min_y);
            }

            Dimension d = this.getSize();
            d.width = (int) max_x + zero;
            d.height = (int) max_y + zero;
            this.setSize(d);
            this.setPreferredSize(d);
        }

        public void markVertices(ArrayList<Vertex> vertices) {
            if (vertices != null) {
                this.cleanMarkedVertices(false);

                //change the vertices' colors
                for (Vertex v : vertices) {
                    v.setSelected(true);
                }

                this.cleanImage();
                this.repaint();
            }
        }

        public void cleanMarkedVertices(boolean cleanVertex) {
            if (graph != null) {
                this.markedVertex = null;

                for (Vertex vertex : graph.getVertex()) {
                    vertex.setSelected(false);

                }
            }

            this.cleanImage();
            this.repaint();
        }

        @Override
        public void setFont(java.awt.Font font) {
            //
        }

        @Override
        public java.awt.Font getFont() {
            return null;// colocar alguma fonte
        }

        @Override
        public void setBackground(Color bg) {
            super.setBackground(bg);

        }
        private java.awt.Color color = java.awt.Color.RED;
        //Used to color based on a document
        private Vertex markedVertex;
        //Used to move the points
        private Vertex selectedVertex;
        //contain the selected vertices which will be moved
        private ArrayList<Vertex> selectedVertices;
        //The image which will be drawn as a graph
        private BufferedImage imageBuffer;

    }
    private ViewPanel view;
    private Graph graph;
    private Grafo grafo;
    private Graph backUpGraph;
    private Grafo backUpGrafo;
    private boolean topologia = false;
    private boolean isLab = false;
    private boolean ap = false;
    private int col;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_busca;
    private javax.swing.JButton bt_caminho;
    private javax.swing.JButton bt_gerar;
    private javax.swing.JButton bt_goMaze;
    private javax.swing.JToggleButton caminhoToggle;
    private javax.swing.JLabel lb_busca;
    private javax.swing.JLabel lb_caminho;
    private javax.swing.JLabel lb_entradaMaze;
    private javax.swing.JLabel lb_gerar;
    private javax.swing.JLabel lb_saidaMaze;
    private javax.swing.JLabel lb_xEntradaMaze;
    private javax.swing.JLabel lb_xSaidaMaze;
    private javax.swing.JLabel lb_yEntradaMaze;
    private javax.swing.JLabel lb_ySaidaMaze;
    private javax.swing.JMenu m_algoritmos;
    private javax.swing.JMenu m_aplicacao;
    private javax.swing.JMenu m_opcoes;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mi_AGM;
    private javax.swing.JMenuItem mi_buscaLargura;
    private javax.swing.JMenuItem mi_caminhoMin;
    private javax.swing.JMenuItem mi_carregarGrafo;
    private javax.swing.JMenuItem mi_coloracao;
    private javax.swing.JMenuItem mi_compConexas;
    private javax.swing.JMenuItem mi_conectividade;
    private javax.swing.JMenuItem mi_criaMaze;
    private javax.swing.JMenuItem mi_maze;
    private javax.swing.JMenuItem mi_ordemTopologica;
    private javax.swing.JMenuItem mi_salvarImagem;
    private javax.swing.JMenuItem mi_transposta;
    private javax.swing.JPanel p_Vazio;
    private javax.swing.JPanel p_busca;
    private javax.swing.JPanel p_caminho;
    private javax.swing.JPanel p_gerar;
    private javax.swing.JPanel p_maze;
    private javax.swing.JPanel p_thePanel;
    private javax.swing.JToggleButton paredeToggle;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField tf_busca;
    private javax.swing.JTextField tf_caminho;
    private javax.swing.JTextField tf_gerar;
    private javax.swing.JTextField tf_xEntradaMaze;
    private javax.swing.JTextField tf_xSaidaMaze;
    private javax.swing.JTextField tf_yEntradaMaze;
    private javax.swing.JTextField tf_ySaidaMaze;
    // End of variables declaration//GEN-END:variables
}
